name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Node Dependencies
        run: npm ci
          
      - name: Copy .env file
        run: cp .env.example .env
          
      - name: Generate key
        run: php artisan key:generate
          
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
          
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Code Style Check
        run: ./vendor/bin/pint --test
          
      - name: Static Analysis
        run: ./vendor/bin/phpstan analyse
          
      - name: Execute Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --parallel